# 부동소수점

In [ ]:
b = 0.35

In [ ]:
b + 0.1

In [ ]:
c = 0.5

In [ ]:
c.as_integer_ratio()

In [ ]:
b.as_integer_ratio()

0.42857142857142855

# decimal 함수로 소수점 정밀도 조절

In [ ]:
import decimal
from decimal import Decimal

In [ ]:
decimal.getcontext()

In [ ]:
d = Decimal(1)/Decimal(11)
d

In [ ]:
1/11

In [ ]:
decimal.getcontext().prec = 4
e = Decimal(1)/Decimal(11)
e

In [ ]:
decimal.getcontext().prec = 50
f = Decimal(1)/Decimal(11)
f

# 문자 정규표현식

In [ ]:
import re

In [ ]:
series = """
'01/18/2014 13:00:00', 100, '1st';
'01/18/2014 13:30:00', 110, '2st';
'01/18/2014 14:00:00', 120, '3st' """

In [ ]:
dt = re.compile("'[0-9/:\s]+'") # datetime

In [ ]:
result = dt.findall(series)
result

In [ ]:
result

In [ ]:
from datetime import datetime
pydt = datetime.strptime(result[0].replace("'", ""),'%m/%d/%Y %H:%M:%S')
pydt

In [ ]:
print(pydt)

In [ ]:
print(type(pydt))

# 튜플

In [ ]:
t = (1,2.5,'data') # 원소 수정 X

In [ ]:
# count 와 index 만 제공

In [ ]:
t.count('data')

In [ ]:
t.index(2.5)

# 리스트 (튜플과 다르게 원소 변경가능)

In [ ]:
l = [2,3.5,'data_']

In [ ]:
l = list(t)

In [ ]:
l

In [ ]:
l.append([4,3]) # 끝에 원소로 추가
l

In [ ]:
l.extend([1.0,1.5,2.0]) # 각각 나누어서 추가
l

In [ ]:
l.insert(1,'insert') # 특정 인덱스 위치에 추가
l

In [ ]:
l.remove('data') # 처음으로 나타나는 원소 삭제
l

In [ ]:
p = l.pop(3) # 특정 인덱스 원소 삭제
l

# 반복문

In [ ]:
m = [i ** 2 for i in range(5)]

In [ ]:
m

In [ ]:
r = list(range(0,8,1))
r

# Function

In [ ]:
def even(x):
    return x % 2 == 0
even(3)

In [ ]:
list(map(even,range(10)))

In [ ]:
list(map(lambda x: x ** 2, range(10))) # 함수 정의 안하고 lambda 쓰면 바로 가능

In [ ]:
list(filter(even,range(15))) # filter - True 가 되는 원소들 모으기

In [1]:
from functools import reduce

In [ ]:
reduce(lambda x,y : x-y,range(1,6)) # reduce 는 내장 함수 아니여서 import 해줘야해
                                     # 그리고 누적 계산이야

# dictionary

In [ ]:
import six

In [ ]:
d = {'name' : 'angela markel',
    'country' : 'germany',
    'age' : 60,
    'name' : 'angela'}

g = dict(a = 1,b = 2,c = 3,d = 2)

In [ ]:
for item in six.iteritems(g):
    print(item)

In [ ]:
for item in six.itervalues(g):
    print(item)

In [ ]:
for value in d.values():
    print(value)

# set

In [ ]:
s = set(['u','d','ud','du','d','du'])
s

In [ ]:
t = set(['d','dd','uu','u'])
t

In [ ]:
s.union(t) # 합집합

In [ ]:
s.intersection(t) # 교집합

In [ ]:
s.difference(t) # s 중 t와 겹치지 않는것

In [ ]:
s.symmetric_difference(t) # 둘중에 하나에만 속하는 것들 모두

In [ ]:
# 리스트 중 중복된 원소를 제거할때 이용하기도함

from random import randint
l = [randint(0,10) for i in range(100)] # 0~10의 임의의 정수 100개 추출

In [ ]:
l[:20]

In [ ]:
set(l)

# Numpy 자료구조

In [ ]:
# list 배열

v = [0.5,0.6,1.0]
m = [v,v,v]
m

In [ ]:
v[0] = 'python'
m

In [ ]:
#이렇게 바뀌는걸 방지하려면 

from copy import deepcopy
v = [0.5,0.6,1.0]
m = 3*[deepcopy(v),]
m

In [ ]:
v[0] = 'python'
m

# 정규 Numpy 배열

In [2]:
import numpy as np
a = np.array([0,0.5,1.0,1.5,2.0])

In [ ]:
a.sum()

In [ ]:
a.std() # 표준편차

In [ ]:
a.cumsum() # 누적합

In [ ]:
a*2

In [ ]:
a**2

In [ ]:
b = np.array([a,a*2])
b

In [ ]:
b.sum(axis = 0) # 열의 합

In [ ]:
b.sum(axis = 1) # 행의 합

In [ ]:
c = np.zeros((2,3,4),dtype = 'i', order = 'C')  # C = 행기반, F = 열기반
c

In [ ]:
d = np.ones_like(c, dtype = 'f8', order = 'C')
d

In [5]:
# Example
import random 
I = 5000
%time mat = [[random.gauss(0,1) for j in range(I)] for i in range(I)]


Wall time: 20.4 s


In [4]:
print(mat[0])

[]


In [6]:
%time reduce(lambda x, y : x + y, [reduce(lambda x,y : x + y,row) for row in mat])

Wall time: 2.35 s


9430.72254264794

In [ ]:
%time mat = np.random.standard_normal((I,I))

In [ ]:
%time mat.sum()

# 구조화 배열

In [3]:
dt = np.dtype([('Name','S10'),('Age','i4'),
              ('Height','f'),('Children/Pets','i4',2)])

In [9]:
s = np.array([('smith',35,1.83,(0,1)),('jones',53,1.72,(2,2))],dtype = dt)

In [10]:
s

array([(b'smith', 35, 1.83, [0, 1]), (b'jones', 53, 1.72, [2, 2])],
      dtype=[('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [11]:
s['Name']

array([b'smith', b'jones'], dtype='|S10')

In [12]:
s['Height'].mean()

1.7750001

# 코드 벡터화

In [13]:
r = np.random.standard_normal((4,3))
s = np.random.standard_normal((4,3))

In [14]:
r+s

array([[ 2.14385848, -1.04683948,  1.58796387],
       [-0.52560989,  0.24086016,  0.65966945],
       [-1.85444215, -0.48595353, -1.47091631],
       [ 1.19276405, -0.00997271,  1.24566016]])

In [15]:
2*r+3

array([[4.4568523 , 1.27417254, 5.91075878],
       [3.62930325, 4.07294653, 4.74035206],
       [2.93998867, 1.72536702, 0.52810818],
       [2.46948314, 3.06361571, 2.68400284]])

In [16]:
s = np.random.standard_normal(3) # 1 x 3 짜리 

In [18]:
r+s # 각 행에 s 를 더해 -> 브로드캐스팅 동작

array([[ 0.08056919, -1.31332607,  1.40049009],
       [-0.33320534,  0.08606093,  0.81528673],
       [-0.67786262, -1.08772883, -1.29083521],
       [-0.91311539, -0.41860448, -0.21288789]])

In [22]:
s = np.random.standard_normal(4)
r+s              # 브로드캐스팅 불가능

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [23]:
r.transpose() + s  # r을 4 x 3 으로 만들면 브로트캐스팅 가능

array([[-0.6914327 ,  0.7437203 , -1.26954141, -0.99916751],
       [-2.28277258,  0.96554194, -1.87685224, -0.70210123],
       [ 0.03552054,  1.29924471, -2.47548165, -0.89190767]])

In [27]:
# 함수에서도 가능

def f(x):
    return 3 * x + 5

print(f(0.5))
print(f(r))

6.5
[[7.18527845 2.41125881 9.36613818]
 [5.94395487 6.60941979 7.61052809]
 [4.90998301 3.08805053 1.29216228]
 [4.20422472 5.09542357 4.52600425]]


In [32]:
# 하지만 math 함수 불가능 / np 함수는 가능

import math

print(np.sin(r))

print(math.sin(r))


[[ 0.66569602 -0.75974037  0.99334686]
 [ 0.30948522  0.51110789  0.76444243]
 [-0.03000116 -0.59504086 -0.94445948]
 [-0.26215867  0.03180249 -0.15734203]]


TypeError: only size-1 arrays can be converted to Python scalars

# 메모리 배치

In [33]:
x = np.random.standard_normal((5,10000000))
y = 2*x+3
C = np.array((x,y), order = 'C')
F = np.array((x,y), order = 'F')
x = 0.0
y = 0.0

In [34]:
%timeit C.sum()
%timeit F.sum() # 전체 합계를 구할땐 차이 거의 없다

141 ms ± 4.35 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
141 ms ± 1.72 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [35]:
%timeit C[0].sum(axis = 0)
%timeit C[0].sum(axis = 1) # 원소 개수가 많은 소수 벡터 더하는게 더 느려

84.6 ms ± 1.42 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
68.6 ms ± 1.54 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [6]:
%timeit F.sum(axis=0)
%timeit F.sum(axis=1) # 원소 개수가 많은 소수 벡터 더하는게 더 빨라

# 하지만 C 방식이 F방식보다 빨라 

1.59 s ± 34.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


3.91 s ± 133 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
