GUI 제작 : traits 라이브러리 사용 but, 클래스 기반으로 빠르게 GUI 개발때 쓰이고 복잡한 어플리케이션에는 안쓰임

URL : https://docs.enthought.com/traits/traits_user_manual/intro.html

# 13.2.1 GUI 가지는 단기 이자율 클래스

In [1]:
import numpy as np
import traits.api as trapi

In [2]:
class short_rate(trapi.HasTraits):
    name = trapi.Str
    rate = trapi.Float
    time_list = trapi.Array(dtype = np.float, shape = (5,))
    
    def get_discount_factors(self):
        return np.exp(-self.rate * self.time_list)

In [3]:
sr = short_rate()

In [4]:
sr.configure_traits()

# name = sr_class
# rate = 0.05
# time_list = 0.0, 0.5, 1.0, 1.5, 2.0

True

In [5]:
sr.name = 'sr_class'
sr.rate = 0.05
sr.time_list = [0.0, 0.5, 1.0, 1.5, 2.0]

In [6]:
sr.rate

0.05

In [7]:
sr.time_list

array([0. , 0.5, 1. , 1.5, 2. ])

In [8]:
sr.get_discount_factors()

array([1.        , 0.97530991, 0.95122942, 0.92774349, 0.90483742])

# 13.2.2 값 갱신하기

결과 표시를 위해 traitsui.api 라이브러리 필요

_update_fired 내부 메서드 -> 리스트 객체를 갱신 -> 갱신된 리스트를 GUI 창에 표시

In [9]:
import traitsui.api as trui

In [10]:
class short_rate(trapi.HasTraits):
    name = trapi.Str
    rate = trapi.Float
    time_list = trapi.Array(dtype = np.float, shape = (1, 5))
    disc_list = trapi.Array(dtype = np.float, shape = (1, 5))
    update = trapi.Button
    
    def _update_fired(self):
        self.disc_list = np.exp(-self.rate * self.time_list)
    
    v = trui.View(trui.Group(trui.Item(name = 'name'),
                             trui.Item(name = 'rate'),
                             trui.Item(name = 'time_list', label = 'Insert Time List Here'),
                             trui.Item('update', show_label = False),
                             trui.Item(name = 'disc_list', label = 'Press Update for Factors'),
                             show_border = True, label = 'Calculate Discount Factors'),
                 buttons = [trui.OKButton, trui.CancelButton],
                 resizable = True)

In [11]:
sr = short_rate()

In [12]:
sr.configure_traits()

True

In [13]:
# GUI 없이 똑같이 동작하는 코드
sr.name = 'sr_class'
sr.rate = 0.05
sr.time_list = np.array(([0.0, 0.5, 1.0, 1.5, 2.0],), dtype = np.float32)

In [14]:
sr._update_fired()

In [15]:
sr.disc_list

array([[1.        , 0.97530991, 0.95122942, 0.92774349, 0.90483742]])

# 13.2.3 GUI 가지는 현금흐름 클래스

In [16]:
class cash_flow_series(trapi.HasTraits):
    name = trapi.Str
    short_rate = trapi.Range(0.0, 0.5, 0.05)
    time_list = trapi.Array(dtype = np.float, shape = (1, 6))
    cash_flows = trapi.Array(dtpye = np.float, shape = (1, 6))
    disc_values = trapi.Array(dtype = np.float, shape = (1, 6))
    present_values = trapi.Array(dtype = np.float, shape = (1, 6))
    net_present_value = trapi.Float
    update = trapi.Button
    
    def _update_fired(self):
        self.disc_values = np.exp(-self.short_rate * self.time_list)
        self.present_values = self.disc_values * self.cash_flows
        self.net_present_value = np.sum(self.present_values)
    
    v = trui.View(trui.Group(trui.Item(name = 'name'),
                             trui.Item(name = 'short_rate'),
                             trui.Item(name = 'time_list', label = 'Time List'),
                             trui.Item(name = 'cash_flows', label = 'Cash Flows'),
                             trui.Item('update', show_label = False),
                             trui.Item(name = 'disc_values', label = 'Discount Values'),
                             trui.Item(name = 'present_values', label = 'Present Values'),
                             trui.Item(name = 'net_present_value', label = 'Net Present Value'),
                             show_border = True, label = 'Calculate Present Values'),
                 buttons = [trui.OKButton, trui.CancelButton],
                 resizable = True)

In [17]:
cfs = cash_flow_series()

In [18]:
cfs.configure_traits()

True

In [19]:
cfs.net_present_value

-0.2926769754325136